### ISSUE TITLE
请问，python版本和依赖版本都是按照requirements_windows.txt来着，但使用 LangChain 调用智谱 AI运行报错

### ISSUE THREAD

**Issue by funcfang** [datawhalechina/llm-universe#41]
**运行这段**
`ai_model.generate(['你好'])`
**报错**
>Traceback (most recent call last):
  File "F:\projects\LangChain_LLM\main.py", line 7, in <module>
    zhipuai_model.generate(['你好'])
  File "E:\develop\miniconda3\envs\LangChain_LLM\lib\site-packages\langchain\llms\base.py", line 603, in generate
    params = self.dict()
  File "E:\develop\miniconda3\envs\LangChain_LLM\lib\site-packages\langchain\llms\base.py", line 929, in dict
    starter_dict = dict(self._identifying_params)
  File "F:\projects\LangChain_LLM\llm\zhipuai_llm.py", line 157, in _identifying_params
    **super()._identifying_params,
  File "F:\projects\LangChain_LLM\llm\zhipuai_llm.py", line 85, in _identifying_params
    return {**{"model_name": self.model_name}, **self._default_params}
  File "F:\projects\LangChain_LLM\llm\zhipuai_llm.py", line 175, in _default_params
    return {**normal_params, **self.model_kwargs}
TypeError: 'FieldInfo' object is not a mapping

有大佬知道啥原因吗

**Comment by funcfang** [comment]
![image](https://github.com/datawhalechina/llm-universe/assets/68361120/284052db-aafc-466f-9f44-4483d61362ef)
暂时不传入 model_kwargs 解决了
